# Generated by Django 4.2.7 on 2026-05-22 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmingTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tip", models.TextField()),
                ("tip_hi", models.TextField(blank=True)),
                ("tip_kn", models.TextField(blank=True)),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("kharif", "Kharif"),
                            ("rabi", "Rabi"),
                            ("zaid", "Zaid"),
                            ("all", "All Seasons"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(default="general", max_length=20)),
                ("icon", models.CharField(default="💡", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuickQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                (
                    "question_hi",
                    models.CharField(blank=True, max_length=300, verbose_name="Hindi"),
                ),
                (
                    "question_kn",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Kannada"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("crop", "Crop Advisory"),
                            ("disease", "Disease & Pest"),
                            ("weather", "Weather"),
                            ("soil", "Soil Management"),
                            ("irrigation", "Irrigation"),
                            ("fertilizer", "Fertilizer"),
                            ("scheme", "Govt Schemes"),
                            ("market", "Market & Mandi"),
                            ("organic", "Organic Farming"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(default="🌾", max_length=10)),
                ("click_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-click_count"],
            },
        ),
        migrations.AlterModelOptions(
            name="chatsession",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="category",
            field=models.CharField(
                choices=[
                    ("crop", "Crop Advisory"),
                    ("disease", "Disease & Pest"),
                    ("weather", "Weather"),
                    ("soil", "Soil Management"),
                    ("irrigation", "Irrigation"),
                    ("fertilizer", "Fertilizer"),
                    ("scheme", "Govt Schemes"),
                    ("market", "Market & Mandi"),
                    ("organic", "Organic Farming"),
                    ("general", "General"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="confidence",
            field=models.FloatField(default=0.95),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="has_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat_images/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_disliked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_voice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="language",
            field=models.CharField(default="en", max_length=5),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="response_time",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="tokens_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="is_starred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("hi", "Hindi"), ("kn", "Kannada")],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="message_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(default="New Conversation", max_length=200),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="session_id",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("voice_enabled", models.BooleanField(default=False)),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("auto_translate", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="chatbot.chatmessage",
                    ),
                ),
            ],
        ),
    ]
