# Generated by Django 4.2.7 on 2026-05-22 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lender_name", models.CharField(max_length=200)),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("crop_loan", "Crop Loan"),
                            ("kcc", "Kisan Credit Card"),
                            ("equipment", "Equipment Loan"),
                            ("land", "Land Purchase Loan"),
                            ("personal", "Personal Loan"),
                            ("cooperative", "Cooperative Loan"),
                            ("microfinance", "Microfinance"),
                            ("other", "Other"),
                        ],
                        default="crop_loan",
                        max_length=50,
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("start_date", models.DateField()),
                ("tenure_months", models.IntegerField()),
                ("emi_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("overdue", "Overdue"),
                            ("restructured", "Restructured"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("purpose", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Livestock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("cow", "Cow (Gaay)"),
                            ("buffalo", "Buffalo (Bhains)"),
                            ("goat", "Goat (Bakri)"),
                            ("sheep", "Sheep (Bhed)"),
                            ("pig", "Pig (Suar)"),
                            ("chicken", "Chicken (Murgi)"),
                            ("duck", "Duck (Batakh)"),
                            ("horse", "Horse (Ghoda)"),
                            ("donkey", "Donkey (Gadha)"),
                            ("camel", "Camel (Oont)"),
                            ("rabbit", "Rabbit (Khargosh)"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("tag_number", models.CharField(max_length=100)),
                ("age_months", models.IntegerField(blank=True, null=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("sick", "Sick"),
                            ("recovering", "Recovering"),
                            ("quarantine", "Quarantine"),
                            ("deceased", "Deceased"),
                        ],
                        default="healthy",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livestock",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("quintal", "Quintal"),
                            ("ton", "Ton"),
                            ("piece", "Piece"),
                            ("dozen", "Dozen"),
                            ("liter", "Liter"),
                            ("bag", "Bag"),
                        ],
                        default="kg",
                        max_length=20,
                    ),
                ),
                (
                    "rate_per_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("buyer_name", models.CharField(blank=True, max_length=200)),
                ("sale_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("received", "Received"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incomes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("seeds", "Seeds"),
                            ("fertilizer", "Fertilizer"),
                            ("pesticide", "Pesticide"),
                            ("irrigation", "Irrigation"),
                            ("labor", "Labor"),
                            ("equipment", "Equipment"),
                            ("fuel", "Fuel"),
                            ("electricity", "Electricity"),
                            ("transport", "Transport"),
                            ("storage", "Storage"),
                            ("maintenance", "Maintenance"),
                            ("veterinary", "Veterinary"),
                            ("feed", "Animal Feed"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CropPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop",
                    models.CharField(
                        choices=[
                            ("wheat", "Wheat (Gehun)"),
                            ("rice", "Rice (Dhan)"),
                            ("maize", "Maize (Makka)"),
                            ("cotton", "Cotton (Kapas)"),
                            ("sugarcane", "Sugarcane (Ganna)"),
                            ("mustard", "Mustard (Sarso)"),
                            ("soybean", "Soybean"),
                            ("chickpea", "Chickpea (Chana)"),
                            ("tomato", "Tomato (Tamatar)"),
                            ("potato", "Potato (Aalu)"),
                            ("onion", "Onion (Pyaz)"),
                            ("groundnut", "Groundnut (Moongfali)"),
                            ("sunflower", "Sunflower"),
                            ("turmeric", "Turmeric (Haldi)"),
                            ("ginger", "Ginger (Adrak)"),
                            ("banana", "Banana (Kela)"),
                            ("mango", "Mango (Aam)"),
                            ("arhar", "Arhar Dal"),
                            ("moong", "Moong Dal"),
                            ("bajra", "Bajra"),
                            ("jowar", "Jowar"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("area_acres", models.DecimalField(decimal_places=2, max_digits=8)),
                ("planting_date", models.DateField()),
                ("expected_harvest", models.DateField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "expected_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("sowing", "Sowing"),
                            ("growing", "Growing"),
                            ("harvesting", "Harvesting"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-planting_date"],
            },
        ),
    ]
